import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import Skilltest from "./skilltest/page";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <div className="w-full border-b border-gray-300 p-4">
            <Navbar />
          </div>

          <div className="h-screen flex flex-row flex-wrap justify-start">
            <div className="h-screen flex flex-row justify-start bg-white border-r border-gray-3">
              <Sidebar />
            </div>
            <div className=" flex-1 p-4 text-black border">
              <h2>{children}</h2>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
